#!/bin/bash
#
# It does not always work: sometimes the iphone goes to sleep and disconnects


#the lag we consider secure in minutes
SECURE_LAG_MIN=10

source /etc/picam.conf

WAIT=5
if [ ! -f $STATEFILE ]; then
    echo "file $STATEFILE does not seem to exist yet... let's $WAIT 10 seconds"
    sleep $WAIT
fi

[ -f $STATEFILE ] || exit 2

changed=$(stat -c %Y "$STATEFILE")
now=$(date +%s)
let max_age_s="$SECURE_LAG_MIN * 60"
let elapsed=now-changed

echo last seen: $changed
echo now: $now
echo max_age_s: $max_age_s
echo elapsed: $elapsed

if [ "$elapsed" -gt "$max_age_s" ]; then
    echo "Area insecure: no friendly presence since $elapsed seconds."
    exit 1
else
    echo "Friendly presence last seen: $elapsed seconds. Still secure."
    cat $STATEFILE
    exit 0
fi
