#!/bin/bash
# This is an example of the check_area_secure script.
# It's actually how I make it work.
# If any of these ip addresses are below, then the area is secure
#
# It does not always work: sometimes the iphone goes to sleep and disconnects

#192.168.4.50  # galaxy s3 mini
#192.168.4.51  # iphone
IP="192.168.4.50 192.168.4.51"
MAX_AGE_MIN=10

STATFILE="/tmp/$(basename $0).stat"

for ip in $IP; do
    ping -c 1 -w 1 $ip > /dev/null
    r=$?
    if [[ "$r" == "0" ]]; then
        # The IP $ip is present. No need to enable
        echo "IP address $ip is present. Touching $STATFILE"
        touch "$STATFILE"
        exit 0
    else
        echo "IP address $ip NOT present"
    fi
done

[ -f $STATFILE ] || exit 2

changed=$(stat -c %Y "$STATFILE")
now=$(date +%s)
let max_age_s="$MAX_AGE_MIN * 60"
let elapsed=now-changed

#echo last seen: $changed
#echo now: $now
#echo max_age_s: $max_age_s
#echo elapsed: $elapsed

if [ "$elapsed" -gt "$max_age_s" ]; then
    echo "No friendly presence."
    exit 1
else
    echo "Last seen: $elapsed seconds. Still secure"
    exit 0
fi
